#!/bin/bash
display=$1
if [[ $display != *:* ]]; then
    echo "You must specify an X display to run on e.g. tcv $DISPLAY"
    exit 1
fi
shift
TF_CPP_MIN_LOG_LEVEL=1 DISPLAY=$display python cli.py $*
